version: "3"
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/frontend/src:/app/src
    env_file:
    	- ./.env
