FROM node:16 as build
WORKDIR /app
COPY ./src/main/frontend/package.json .
RUN npm install
COPY ./src/main/frontend/ .
RUN npm run build

FROM nginx:latest
COPY --FROM=build /app/build/ /usr/share/nginx/html
