version: "3"
services:
  msc_frontend:
    image: jsuryadharma/msc_frontend:latest
    container_name: msc_frontend
    ports:
      - "3000:3000"
  msc_backend:
    image: jsuryadharma/msc:latest
    container_name: msc
    depends_on:
      - msc_frontend
    ports:
      - "8080:8080"
